version: "3.2"

volumes:
  db_data : {}

services:

  php74:
    build: 
      context: ./bin/php74
    restart: always
    container_name: php74
    ports:
      - "8074:80"
    volumes:
      - ./public_html:/var/www/html
      - ./apache/php72:/var/log/apache2
    links: 
      - db:database

  php56:
    build: 
      context: ./bin/php56
    restart: always
    container_name: php56
    ports:
      - "8056:80"
    volumes:
      - ./public_html:/var/www/html
      - ./apache/php56:/var/log/apache2
    links: 
      - db:database

  php52:
    image: deminy/php-5.2
    restart: always
    container_name: php52
    ports:
      - "8052:80"
    volumes:
      - ./public_html:/project
      - ./apache/php52:/var/log/apache2
    links: 
      - db:database

  db:
    image: mysql:5.5
    restart: always
    container_name: mysql55
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=111111
    ports:
      - 8306:3306
    volumes:
      - db_data:/var/lib/mysql/root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    links: 
      - db